"""empty message

Revision ID: 563d3ce7c5ce
Revises: ae771267f249
Create Date: 2023-09-28 19:27:18.328477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563d3ce7c5ce'
down_revision = 'ae771267f249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_status', sa.Enum('0', '1'), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_status')

    # ### end Alembic commands ###
