"""empty message

Revision ID: ae771267f249
Revises: 
Create Date: 2023-09-24 09:46:05.694439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae771267f249'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=20), nullable=False),
    sa.Column('admin_pwd', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_username')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=60), nullable=False),
    sa.Column('category_image', sa.String(length=200), nullable=False),
    sa.Column('category_icon', sa.String(length=200), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=60), nullable=False),
    sa.Column('user_password', sa.String(length=200), nullable=False),
    sa.Column('user_registration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('survey',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('survey_name', sa.String(length=60), nullable=False),
    sa.Column('survey_status', sa.Enum('1', '0'), server_default='0', nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.survey_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.survey_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('option',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_table('response_question',
    sa.Column('response_question_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['option.option_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.response_id'], ),
    sa.PrimaryKeyConstraint('response_question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_question')
    op.drop_table('option')
    op.drop_table('response')
    op.drop_table('question')
    op.drop_table('survey')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
